### ISSUE TITLE
_links voor adres zoeken onjuist gemodelleerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#101]
ZoekResultaatHalCollectie is de _links nu als volgt vormgegeven:
```
        _links:
          type: object
          properties:
            self:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink'
              description: 'Refereert naar de /adressen/zoeken endpoint met de zoekterm als parameter'
            adres:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalPaginationLinks'
              description: 'Gepagineerde lijst van links naar zoekresultaten via een templated URI en met een zoekresultaat identificatie.'
```

Hierin is een property adres opgenomen in de _links met daarin HAL-link properties self, first, previous en next. Self is dus twee keer opgenomen in de _links, en de pagineerlinks zijn onnodig in een extra laag opgenomen.

Ik zou dit definiëren als:
```
        _links:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalPaginationLinks'
```
