### ISSUE TITLE
parameters op identificaties moeten geen businesslogica hebben in het pattern

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#140]
op alle parameters voor identificaties is nu een pattern opgenomen die specifiek is voor het soort identificatie en de logica die het Kadaster toepast bij het samenstellen van de identificaties.

Bijvoorbeeld:
```
    nummeraanduidingidentificatie-query:
      description: Identificatie van een nummeraanduiding uit de BAG. Deze is 16 cijfers lang.
      name: nummeraanduidingidentificatie
      in: query
      required: false
      schema:
        type: string
        pattern: '^[0-9]{4}20[0-9]{10}$'
        example: '1234200000000001'
```

Hier wordt door het pattern afgedwongen dat op posities 5 en 6 altijd "20" staat.

Dit is "implementation bleed" die tight coupling tussen de bronregistratie en de API tot gevolg heeft. Voor de gebruiker moet het niet relevant zijn welk algoritme BAG heeft gebruikt voor het samenstellen van de identificaties. Het moet voor BAG ook mogelijk zijn voor toekomstige objecten een andere logica te gebruiken voor nieuwe identificaties. Dat mag dan geen breaking change opleveren.

Ik denk dat een pattern dat afdwingt dat er alleen cijfers moeten zijn voldoende is, of desnoods dat het 16 cijfers moeten zijn. De gebruiker wordt er dan op een nette manier op geattendeerd wanneer bijvoorbeeld een cijfer vergeten is.
Of een gebruiker nu een onjuist cijfer heeft getypt op positie 6, of op positie 7 maakt niet uit. Beide leiden tot een 404 (niet gevonden) in geval van een path-parameter, of geen resultaat in geval van een query-parameter. Ik stel dus voor de parameters m.b.t. alle identificaties (niet alleen hier op adres) algemener te maken, zonder vastgestelde waarde voor posities 5 en 6.
