### ISSUE TITLE
Waarom moet een point gezocht worden met een POST?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#146]
Er is nu een operatie POST /panden gedefinieerd om te zoeken op een punt. Waarom kan dat niet in GET /panden? Dus als queryparameter? Het gaat immers om een point, dus twee coordinaten

Je zou deze kunnen definieren als queryparameter:
```
        - in: query
          required: false
          name: coordinates:
          explode: false
          schema:
            type: array
            minItems: 2
            items:
              type: number
```
