### ISSUE TITLE
examples moeten niet tussen quotes wanneer het property een integer is

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#163]
examples worden nu (terecht) tussen quotes gezet. Alleen wanneer het property is gedefinieerd als integer dan klopt het niet om deze tussen quotes te zetten. Daarmee wordt het example namelijk een string.

Bijvoorbeeld in AdresBasis en in Nummeraanduiding:
```
        huisnummer:
          description: Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende nummering.
          title: huisnummer
          type: integer
          example: '12'
```
