### ISSUE TITLE
Onterecht accept-crs verplicht

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#240]
wanneer een request wordt gedaan naar /adresseerbareobjecten/0599010000165822, zonder de request header Accept-Crs, wordt de volgende foutmelding gegeven:
```
{
   "status" : 412,
   "type" : "https://tools.ietf.org/html/rfc7232#section-4.2",
   "detail" : "Header: Accept-Crs moet aanwezig zijn",
   "instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0599010000165822"
}
```

Dit is m.i. niet terecht, want deze header is niet required én er is een default gedefinieerd:
```
      - name: Accept-Crs
        in: header
        description: Gewenste CRS van de coördinaten in de response.
        required: false
        schema:
          type: string
          description: CRS van de coördinaten in de response. epsg:28992 mapt op het
            RD New Nederlands coordinatenstelsel.
          default: epsg:28992
          enum:
          - epsg:28992
```
