### ISSUE TITLE
Code generatie o.b.v. verblijfsobject YAML genereert objecten met errors

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#26]
# Impediment

Gegenereerd via https://editor.swagger.io/
Gekozen voor 'Generate Server' en dan 'aspnetcore'

Bij het genereren van de verblijfsobject API specificaties in C# ontstaan er **150**+ build errors.
Voorbeeld hiervan is het enum object InOnderzoekNummeraanduiding.
```
/*
 * IMBAG API - van de LVBAG
 *
 * \"Dit is de BAG API van de landelijke voorziening BAG (LVBAG) voor het informatiemodel IMBAG 2.0 en conform de API strategie 1.1 specificatie in OAS3. Deze is vooral gericht op individuele bevragingen (op basis van de identificerende gegevens van een object).  <br/><br/> <font color='red'>**LET OP: Deze specificatie is een \\\"work in progress\\\"**, oftewel niet definitief.</font><br/><br/> Meer informatie over BAG 2.0 is te vinden op: [Catalogus BAG 2.0](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen) <br/> Meer informatie over Nederlandse API strategie is te vinden op: [API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie) - deze API volgt versie 1.1 van 20190213.  <br/> Meer informatie over OAS3 specificatie is te vinden op: [OAS](https://www.forumstandaardisatie.nl/standaard/openapi-specification)   <br/> Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks. <br/> <br/> Voor vragen, neem contact op met de BAG beheerder o.v.v. BAG API 2.0. We zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets (nog) niet kan, wat u wel graag wilt, neem dan contact op.  <br/> <br/> Een API-key kan  verkregen worden door een e-mail te sturen naar: zie onderstaande contactgegevens <font color='blue'>send e-mail</font>.\" 
 *
 * OpenAPI spec version: 0.1
 * Contact: bag@kadaster.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets InOnderzoekNummeraanduiding
        /// </summary>
        
        public enum InOnderzoekNummeraanduiding
        {
            /// <summary>
            /// Enum HuisnummerEnum for huisnummer
            /// </summary>
            
            HuisnummerEnum = huisnummer,
            /// <summary>
            /// Enum HuisletterEnum for huisletter
            /// </summary>
            
            HuisletterEnum = huisletter,
            /// <summary>
            /// Enum HuisnummertoevoegingEnum for huisnummertoevoeging
            /// </summary>
            
            HuisnummertoevoegingEnum = huisnummertoevoeging,
            /// <summary>
            /// Enum PostcodeEnum for postcode
            /// </summary>
            
            PostcodeEnum = postcode,
            /// <summary>
            /// Enum TypeAdresseerbaarObjectEnum for type adresseerbaar object
            /// </summary>
            
            TypeAdresseerbaarObjectEnum = type adresseerbaar object,
            /// <summary>
            /// Enum StatusEnum for status
            /// </summary>
            
            StatusEnum = status,
            /// <summary>
            /// Enum LigtInEnum for ligt in
            /// </summary>
            
            LigtInEnum = ligt in,
            /// <summary>
            /// Enum LigtAanEnum for ligt aan
            /// </summary>
            
            LigtAanEnum = ligt aan        }
}
```

Alle enum waardes worden hier zonder quotes geregistreerd. Dit is vrij simpel omdat het in de specificaties niet correct staat.

```
    InOnderzoekNummeraanduiding:
      title: InOnderzoekNummeraanduiding
      type: string
      enum:
      - huisnummer
      - huisletter
      - huisnummertoevoeging
      - postcode
      - type adresseerbaar object
      - status
      - ligt in
      - ligt aan
```

Zoals hierboven te zien is, zijn deze zonder quotes gedefinieërd en worden dus ook niet via de generating tool geplaatst.

Voorbeeld uit BRP API waar generatie van enum succesvol is afgerond:
```
        /// <summary>
        /// : * `I` - Ingehouden, ingeleverd * `V` - Vermist * `R` - Rechtswege * `.` - Onbekend
        /// </summary>
        /// <value>: * `I` - Ingehouden, ingeleverd * `V` - Vermist * `R` - Rechtswege * `.` - Onbekend</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AanduidingInhoudingVermissingReisdocumentEnum
        {
            /// <summary>
            /// Enum IEnum for I
            /// </summary>
            [EnumMember(Value = "I")]
            IEnum = 0,
            /// <summary>
            /// Enum VEnum for V
            /// </summary>
            [EnumMember(Value = "V")]
            VEnum = 1,
            /// <summary>
            /// Enum REnum for R
            /// </summary>
            [EnumMember(Value = "R")]
            REnum = 2,
            /// <summary>
            /// Enum Period for .
            /// </summary>
            [EnumMember(Value = ".")]
            Period = 3        }
```
Hieronder zoals gespecificeerd in BRP API:
```
    AanduidingInhoudingVermissingReisdocument_enum:
      type: "string"
      description: "De mogelijke waarden van de aanduiding van inhouding of vermissing\
        \ van een Nederlands reisdocument. Zie logisch ontwerp BRP bij de stamtabellen:\n\
        * `ingehouden_of_ingeleverd` - I\n* `vermist` - V\n* `rechtswege` - R\n* `niet_in_bezit_van`\
        \ - N"
      enum:
      - "ingehouden_of_ingeleverd"
      - "vermist"
      - "rechtswege"
      - "niet_in_bezit_van"
```
