### ISSUE TITLE
Pagination headers niet correct

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#310]
In de response bij /adressen/zoek zitten de headers:
X_pagination_limit: 20
X_pagination_page: 1

In de specificaties zijn deze opgenomen als X-Pagination-Limit en X-Pagination-Page. Dus met "-" (min-teken) i.p.v. "_" (underscore).

**Comment by fsamwel** [comment]
voor release 1.0.0 verwijder ik de pagination headers uit de specs. Die zijn nu ook niet op alle plekken gedefinieerd waar wel paginering voorkomt.
Voor release 1.1.0 kunnen we dan overwegen om de headers toe te voegen, wanneer ook de juiste geleverd worden.

**Comment by strijm** [comment]
In de HC common.yaml staan deze headers met een '_', dus niet met een '-'. Er hadden echter wel hoofdletters gebruikt moeten worden (bv. X_Pagination_Limit i.p.v. X_pagination_limit).

**Comment by fsamwel** [comment]
> In de HC common.yaml staan deze headers met een '_', dus niet met een '-'. Er hadden echter wel hoofdletters gebruikt moeten worden (bv. X_Pagination_Limit i.p.v. X_pagination_limit).

In de BAG specificatie staat:

```
            X-Pagination-Page:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.1.0/api-specificatie/common.yaml#/components/headers/X_Pagination_Page'
            X-Pagination-Limit:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.1.0/api-specificatie/common.yaml#/components/headers/X_Pagination_Limit'
```

De definitie daarvan wordt gehaald uit een common.yaml component met de naam resp. "X_Pagination_Page" en "X_Pagination_Limit" (dus met underscores). Waar het hier om gaat is niet de naam van de schemacomonent, maar de naam van de header zelf. 

Bij de api-version response header is dit op deze manier (zoals ik het verwacht) geïmplementeerd:
```
          headers:
            api-version:
              $ref: '#/components/headers/api_version'
```
De API levert de header "api-version", niet "api_version.
