### ISSUE TITLE
eenvoudiger modelleren in onderzoek staan van gegevens

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#75]
In onderzoek is nu gemodelleerd als array met 5 properties:
- identificatieVan...
- kenmerk
- indicatieInOnderzoek
- documentdatum
- documentnummer

Er is geen behoefte aan documentdatum en documentnummer. de identificatieVan... is overbodig, want het onderzoek gaan, in het perspectief van de gebruiker, altijd over betreffende resource.

Dus gaat het alleen om welke properties in onderzoek zijn.

Voorstel is om in onderzoek te definiëren met alle properties van de resource, voor zover ze in onderzoek kunnen staan. De gebruiker weet dan uit de yaml al welke properties zij/hij kan verwachten. Elk property is dan als boolean gedefinieerd, met waarde true wanneer het gegeven in onderzoek is (en weglaten wanneer het gegeven niet in onderzoek is).

Bijvoorbeeld:
```
OpenbareRuimteInOnderzoek:
      type: object
      description: "Een groep van booleans om aan te geven welke gegevens van de openbare\
        \ ruimte in onderzoek zijn. Wanneer een gegeven hier is opgenomen met de waarde true, dan is het corresponderende gegeven van deze openbare ruimte in onderzoek."
      properties:
        identificatie:
          type: boolean
        naam:
          type: boolean
        type:
          type: boolean
        verkorteNaam:
          type: boolean
        geconstateerd:
          type: boolean
```
